# Generated by Django 5.0 on 2025-03-09 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chargehebdomadaire',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chargehebdomadaire',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.filiere'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='modifications_ouvertes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chargehebdomadaire',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.groupe'),
        ),
        migrations.AlterUniqueTogether(
            name='chargehebdomadaire',
            unique_together={('semaine', 'matiere', 'filiere', 'groupe')},
        ),
    ]
